import localFont from "next/font/local";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PoetsenOne = localFont({
  src: "../public/fonts/PoetsenOne.ttf",
  display: "swap",
});

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={PoetsenOne.className}>
      <body className="flex p-12 justify-center h-screen w-full bg-black">
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
